version: 2
 jobs:
   one:
     docker:
       - image: circleci/python:3.7.4
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 10
   two:
     docker:
       - image: circleci/python:3.7.4
     steps:
       - checkout
       - run: echo "A more familiar hi"
       - run: sleep 15
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two