version: 2
jobs:
 simple_tf_build:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - checkout
     - run: terraform init
     - run: terraform plan -input=false -out=tfplan
     - run: terraform apply -input=false tfplan
