version: 2
jobs:
 simple_tf_build:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - run: terraform init
     - run: terraform plan -input=false -out=tfplan
     - run: terraform apply -input=false tfplan
workflows:
 version: 2
 one_and_two:
   jobs:
     - checkout
     - simple_tf_build
