version: 2
jobs:
 one:
   docker:
     - image: circleci/python:3.7.4
   steps:
     - checkout
     - run: echo "A first hello"
     - run: sleep 10
 two:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - checkout
     - run: terraform init
     - run: terraform plan
     - run: terraform apply
workflows:
 version: 2
 one_and_two:
   jobs:
     - one
     - two
