version: 2
jobs:
 validate:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - checkout
     - run: terraform init
 plan_apply:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - checkout
     - run: terraform init
     - run: terraform plan -input=false -out=tfplan
     - run: terraform apply -input=false tfplan
workflows:
 version: 2
 tf_build:
   jobs:
     - validate
     - plan_apply:
         requires:
           - validate
