version: 2
jobs:
 validate:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - run: terraform init
 plan:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - run: terraform init
     - run: terraform plan -input=false -out=tfplan
 apply:
   docker:
     - image: hashicorp/terraform:0.12.14
   steps:
     - run: terraform apply -input=false tfplan
workflows:
 version: 2
 tf_build:
   jobs:
     - checkout
     - validate:
         requires:
           checkout
     - plan:
         requires:
           validate
     - apply:
         requires:
           plan
